url: https://ethanagbaker.github.io
#baseurl: /agency-jekyll-theme/

# Site settings
title: Ethan Alexander Garc&iacute;a Baker
email: ethanagbaker+website@gmail.com
description: "Ethan A"
# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503  
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Ethan 
  pic: 1
  position: Lead Designer
  social:
     - title: twitter
    url: http://twitter.com/ethanabaker
     - title: linkedin
    url: https://www.linkedin.com/in/ethanagbaker
     - title: github
     url: http://github.com/ethanagbaker


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ethanabaker
  - title: linkedin
    url: https://www.linkedin.com/in/ethanagbaker
  - title: github
    url: http://github.com/ethanagbaker

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty