# Site Settings
title:               Ethan Alexander Garc&iacutea Baker
tagline:             computational biologist
description:
baseurl:
url:
github:
  url:               
author:
  name:              "Ethan Alexander García Baker"
  email:             "ethanagbaker@gmail.com"
  twitter:           "ethanagbaker"
  github:            "ethanagbaker"
  facebook:          "ethanabaker1"
  linkedin:          "ethanagbaker"
navigation:
- title: about
  url: /about
- title: research
  url: /research
- title: journal
  url: /journal
- title: contact
  url: /contact

paginate:            5
disqus:              "ethanagbaker"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           journal/:title/
gems:                [jekyll-paginate]
