# Site settings
title: Ethan Alexander Garc&iacute;a Baker
email: ethanagbaker@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Scientist, philosopher, bioinformatician, student, TBD.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ethanagbaker.github.io/" # the base hostname & protocol for your site
twitter_username: ethanabaker
github_username:  ethanagbaker

# Build settings
markdown: kramdown
